name: Imaginese
favicon: null
layout_spectrum: 0.9759997560176998
typography_spectrum: 0.41294730035588145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b13'
    - '#67221b'
    - '#b8b7b8'
    - '#687b29'
  brandStrength: 0.5625
  lightness: 0.26030757487751544
  saturation: 0.3289627465419471
  rhythmicContrast: 0.021635975455865264
purpose: []
