name: Imaginese
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b13'
    - '#67221b'
    - '#b8b7b8'
    - '#687b29'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
